### ISSUE TITLE
Simply "metadata" ?

### ISSUE THREAD

**Issue by IanLee1521** [doecode/software-metadata#1]
Would the name of this repo be better simply as the shorter "metadata" instead of "software-metadata"?

@jayjaybillings  -- Thoughts?

**Comment by keknight** [comment]
I could see changing the name in case the schema is extended later. I included the "Software" class in case we or someone else wanted to extend the schema to include data sets, etc. sometime later but still wanted to differentiate between types of resources within the system (rdfs:Resource is the super class of dctype:Software, so any other "resource" type class could be added to the schema later--ditto for agents and concepts).

**Comment by jayjaybillings** [comment]
I figured we would change it later if we needed it, but for now I thought it better to make it clear what kind of metadata we were really looking at.

**Comment by IanLee1521** [comment]
I agree. (Jay and I'd talked yesterday about it). Thanks for the insight!
